### ISSUE TITLE
模型对于文档图片学习能力如何？

### ISSUE THREAD

**Issue by fengyanWang** [zhangXJ147/Latent-SDE#1]
请问模型可以学到如下图片之间的特征转换关系吗？即：输入图片为原始文档图片，输出图片包含对输入图片进行美化和去手写。
然后请问该模型性能如何，生成一张640 * 640的图片耗时要多久（比如：在4090ti机器上）
![file006_5](https://github.com/user-attachments/assets/3d03775f-b3aa-43aa-9dce-9830cb4f0939)
![file006_5](https://github.com/user-attachments/assets/a2b68d4e-59e8-41d0-b9a4-61ecce532609)

**Comment by zhangXJ147** [comment]
你好，我们没有做这方面的研究，但我们公开了代码和训练过程，你可以在自己的任务上试一试。我们在一张A100上面生成20张256X256图片的时间大约为183秒。

**Comment by fengyanWang** [comment]
> 你好，我们没有做这方面的研究，但我们公开了代码和训练过程，你可以在自己的任务上试一试。我们在一张A100上面生成20张256X256图片的时间大约为183秒。

谢谢大佬回复，我这边试试！
